<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Tests.OpenTelemetry</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\OpenTelemetry\OpenTelemetry.csproj" />
        <ProjectReference Include="..\Tests.Shared\Tests.Shared.csproj" />
    </ItemGroup>

</Project>
