<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>$(CoreVersion)</Version>
        <AssemblyName>Aurore.Foundation.Core</AssemblyName>
        <RootNamespace>Aurore.Foundation.Core</RootNamespace>
        <Product>Aurore Foundation @ Core</Product>
        <Description>Dependency-light core and common utilities for aurore projects.</Description>
        <PackageTags>aurore core abstractions utilities helpers</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Humanizer.Core" Version="3.0.10" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
        <PackageReference Include="Sqids" Version="3.2.1" />
    </ItemGroup>

</Project>
