<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>$(OpenTelemetryVersion)</Version>
        <AssemblyName>Aurore.Foundation.OpenTelemetry</AssemblyName>
        <RootNamespace>Aurore.Foundation.OpenTelemetry</RootNamespace>
        <Product>Aurore Foundation @ OpenTelemetry</Product>
        <Description>OpenTelemetry extensions and utilities for aurore projects.</Description>
        <PackageTags>aurore opentelemetry extensions utilities helpers</PackageTags>

        <!-- Required for OpenTelemetry packages that are on beta -->
        <WarningsNotAsErrors>$(WarningsNotAsErrors);NU5104</WarningsNotAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenTelemetry" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.15.1-beta.1" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="1.15.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.17.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>

</Project>
